name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile_mysql --tag mysql
    - name: Deploy to ECR
      # You may pin to the exact commit or the version.
      # uses: rahulrkr08/gh-aws-deploy@790400a8501a2626d17d7a3c230a3355a90835d0
      uses: rahulrkr08/gh-aws-deploy@v3
      with:
        # Access key for IAM User.
        access-key-id: ASIAZTVGSY6R6LS3IJVT
        # Secret access key for IAM User.
        secret-access-key: bwMty1+g15/jihT8BYFKctvtJhpDFlcxAbLHH5/R
        # AWS Region to use.
        region: us-east-1
      
    - name: AWS ECR
  # You may pin to the exact commit or the version.
  # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
      uses: kciter/aws-ecr-action@v4
      with:
        # The AWS access key id
        access_key_id: ASIAZTVGSY6R6LS3IJVT
        account_id: 660700579747
        # The AWS secret access key
        secret_access_key: bwMty1+g15/jihT8BYFKctvtJhpDFlcxAbLHH5/R
        aws_session_token: FwoGZXIvYXdzEKf//////////wEaDAWuAybp1S7oQsrywSK9AXqK0bJnoib7XVhCv5h4pd41u31XCnJCE05HZD4c3jaJkxFEFbM7YhUCshg/PEmU8LTTBR259JkqgqB5U+2BtaCafawLLCFJlTJHfw3Or0nlHYyZ0BP7eV7rSyZC0y+y6HSAsFRZRVYIb02pgx5tEqJKr+IpJ7vcFnEuLF//+uHIuRheYYAkV5cD0TeEU8Ny9F1iaTGwo2SOd9Lh4tyYcnvQxhJwr8Eio2gnoN0bGqL7KBT3H/AXV/DIh1UPWCiJqdiZBjItZvI4dY6dnny+WuhcHnqsBVJW1Nsv5aN9LFIgZ4ROnYqPq16t5uFCgkAnVLtT
        repo: assignment1ecr
        region: us-east-1
